/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vkı_hesaplama;

import java.text.DecimalFormat;

/**
 *
 * @author user
 */
public class HESAPLAMA extends javax.swing.JFrame {

  double boyu ,kilosu,ideal_kilo,sonuc;
  DecimalFormat formatter = new DecimalFormat("###,###.###");
    public HESAPLAMA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kilo = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        boy = new javax.swing.JTextPane();
        hesapla = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cikti = new javax.swing.JTextPane();
        kadin = new javax.swing.JRadioButton();
        erkek = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Cinsiyet :");

        jLabel2.setText("Kilonuzu Giriniz (kg) :");

        jLabel3.setText("Boyunuzu Giriniz (orn: 1.65)");

        jScrollPane2.setViewportView(kilo);

        jScrollPane3.setViewportView(boy);

        hesapla.setBackground(new java.awt.Color(51, 51, 255));
        hesapla.setText("HESAPLA");
        hesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesaplaActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(cikti);

        kadin.setBackground(new java.awt.Color(204, 204, 204));
        kadin.setText("Kadin");
        kadin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kadinActionPerformed(evt);
            }
        });

        erkek.setBackground(new java.awt.Color(204, 204, 204));
        erkek.setText("Erkek");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(erkek)
                            .addComponent(kadin))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hesapla)
                        .addGap(27, 27, 27))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(kadin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(erkek))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hesapla)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kadinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kadinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kadinActionPerformed

    private void hesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesaplaActionPerformed
        
        boyu=(Double.parseDouble(String.valueOf(boy.getText())));
         kilosu=(Double.parseDouble(String.valueOf(kilo.getText())));
         sonuc = kilosu/(boyu*boyu);
         if(kadin.isSelected())
         {
             ideal_kilo =45.5+ 2.3*((boyu*100)/2.54-60);
         }
         if(erkek.isSelected())
         {
             ideal_kilo =50+ 2.3*((boyu*100)/2.54-60);
         }
         if(sonuc<18.5)
         {
        cikti.setText("Vücut Kitle İndeksiniz: "+String.valueOf(formatter.format(sonuc))+"\n"+
                      "Vücut kitle indeksinize göre durumunuz : ZAYIF "+"\n"+
                      "İdeal Kilonuz : "+String.valueOf(Math.ceil(ideal_kilo)));
         } 
         else if(sonuc>=18.5&&sonuc<25) 
         {
    cikti.setText("Vücut Kitle İndeksiniz: "+String.valueOf(formatter.format(sonuc))+"\n"+
                      "Vücut kitle indeksinize göre durumunuz : NORMAL "+"\n"+
                      "İdeal Kilonuz : "+String.valueOf(Math.ceil(ideal_kilo)));
         } 
         else if(sonuc>=25&&sonuc<28) 
         {
    cikti.setText("Vücut Kitle İndeksiniz: "+String.valueOf(formatter.format(sonuc))+"\n"+
                      "Vücut kitle indeksinize göre durumunuz : KİLOLU-RİSKLİ "+"\n"+
                      "İdeal Kilonuz : "+String.valueOf(Math.ceil(ideal_kilo)));
         } 
         else if(sonuc>=28&&sonuc<30) 
         {
    cikti.setText("Vücut Kitle İndeksiniz: "+String.valueOf(formatter.format(sonuc))+"\n"+
                      "Vücut kitle indeksinize göre durumunuz: KİLOLU-OLDUKÇA OBEZ "+"\n"+
                      "İdeal Kilonuz : "+String.valueOf(Math.ceil(ideal_kilo)));
         } 
         else if(sonuc>=30) 
         {
    cikti.setText("Vücut Kitle İndeksiniz: "+String.valueOf(formatter.format(sonuc))+"\n"+
                      "Vücut kitle indeksinize göre durumunuz: KİLOLU-AŞIRI OBEZ "+"\n"+
                      "İdeal Kilonuz : "+String.valueOf(Math.ceil(ideal_kilo)));
         } 
         else 
         {
    System.out.println("Hata oluştu");
         }
         //cikti.setText("hello : "+String.valueOf(sonuc));
    }//GEN-LAST:event_hesaplaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HESAPLAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HESAPLAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HESAPLAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HESAPLAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HESAPLAMA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane boy;
    private javax.swing.JTextPane cikti;
    private javax.swing.JRadioButton erkek;
    private javax.swing.JButton hesapla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton kadin;
    private javax.swing.JTextPane kilo;
    // End of variables declaration//GEN-END:variables
}
